baseURL = 'https://yuushaexa.github.io/'
languageCode = 'en-us'
title = "GameLibrary"
theme = "bloggeri"
paginate = 10
[params]
    description = "My site description"
    author = "Janne"
    authorImage = "https://howlongtobeat.com/games/Twinbee_flyer.png?width=250"
[markup]
    defaultMarkdownHandler = "goldmark"

    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
            
            [outputs]
home = [ "HTML", "RSS", "JSON" ]
            
            [taxonomies]
    tag = "tags"
    category = "categories"

 [[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Blog"
  url = "/blog"
  
  [[menu.main]]
    name = "Categories"
    url = "/categories"

  [[menu.footer]]
  name = "About"
  url = "/about"

[[menu.footer]]
  name = "Privacy"
  url = "/privacy"

[[menu.main]]
  name = "Search"
  identifier = "search"
  url = "/search"
