baseURL = 'https://yuushaexa.github.io/Full-website/'
languageCode = 'en-us'
title = "GameLibrary"
theme = "bloggeri" 
paginate = 50
summarylength = 10
[params]
    description = "Games Library"
    author = "Yuusha"
    [security]
[security.gotemplates]
allowActionJSTmpl = true
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
            [outputs]
home = [ "HTML", "RSS", "JSON" ]
            
            [taxonomies]
    tag = "tags"
    category = "categories"
    genres = "genres"
    publisher = "publisher"
    developer = "developer"
    gametype = "gametype"
    year = "year"
    
 [[menu.main]]
  name = "About"
  url = "/about/"

[[menu.main]]
  name = "Famicom"
  url = "/famicom/"
  
  [[menu.main]]
  name = "SNES"
  url = "/snes/"
  
  [[menu.main]]
    name = "Categories"
    url = "/categories/"

 [[menu.main]]
  name = "Account"
  url = "/account/"

     [[menu.main]]
    name = "Favorites"
    url = "/favorites/"

    [[menu.main]]
    name = "register"
    url = "/register/"

  [[menu.footer]]
  name = "About"
  url = "/about/"

[[menu.footer]]
  name = "Privacy"
  url = "/privacy/"

[[menu.main]]
  name = "Search"
  identifier = "search"
  url = "/search/"

[related]
    threshold = 100 
    includeNewer = true
    toLower = false
        
[[related.indices]]
        name = "publisher"
        weight = 80

        [[related.indices]]
        name = "genres"
        weight = 20

[params.widget.regionCodes]
  1 = "europe"
  2 = "north_america"
  3 = "australia"
  4 = "new_zealand"
  5 = "japan"
  6 = "china"
  7 = "asia"
  8 = "worldwide"
  9 = "korea"
  10 = "brazil"

[module]
  [[module.mounts]]
    source = "prebuild/public/"
    target = "content"
# target = 'content/anything' to change url
