baseURL = 'https://yuushaexa.github.io/'
languageCode = 'en-us'
title = "GameLibrary"
theme = "bloggeri"
paginate = 2000
summarylength = 10
[params]
    description = "Games Library"
    author = "Yuusha"
[markup]
    defaultMarkdownHandler = "goldmark"

    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

            [outputs]
home = [ "HTML", "RSS", "JSON" ]
            
            [taxonomies]
    tag = "tags"
    category = "categories"
    genres = "genres"
    publisher = "publisher"
    developer = "developer"
    gametype = "gametype"
    year = "year"
    
 [[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Famicom"
  url = "/famicom"
  
  [[menu.main]]
  name = "SNES"
  url = "/snes"
  
  [[menu.main]]
    name = "Categories"
    url = "/categories"

  [[menu.footer]]
  name = "About"
  url = "/about"

[[menu.footer]]
  name = "Privacy"
  url = "/privacy"

[[menu.main]]
  name = "Search"
  identifier = "search"
  url = "/search"

[related]
    threshold = 100 
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "developer"
        weight = 50

