baseURL = 'https://yuushaexa.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "bloggeri"
[params]
    description = "My site description"
    author = "Janne"
    authorImage = "https://howlongtobeat.com/games/Twinbee_flyer.png?width=250"
[markup]
    defaultMarkdownHandler = "goldmark"

    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
            
            [outputs]
home = [ "HTML", "RSS", "JSON" ]
            
            [taxonomies]
    tag = "tags"
    category = "categories"

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "title"
    weight = 20

 [[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Blog"
  url = "/blog"
  
  [[menu.main]]
    name = "Categories"
    url = "/categories"

  [[menu.footer]]
  name = "About"
  url = "/about"

[[menu.footer]]
  name = "Privacy"
  url = "/privacy"

  [[menu.social]]
    name = "GitHub"
    url = "https://github.com/pakstech"
    pre = "<i class='fab fa-github'></i>"

[[menu.social]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCg_e3UBPs-BxPo_jVg1gGOQ"
    pre = "<i class='fab fa-youtube'></i>"

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/pakstech"
    pre = "<i class='fab fa-twitter'></i>"
