# config.yaml
disableKinds:
- sitemap
- taxonomy
- term
outputs:
  home:
  - html
module:
  mounts:
  - source: content
    target: content
  - source: prebuild/public/monster
    target: content/monster
